title: Home Grid Image

accept: 
  type: image


columns:
  - width: 1/2
    sections:
      content:
        type: fields
        fields:
          caption:
            label: Caption
            type: text
            size: medium
  - width: 1/2
    sections:
      meta:
        type: fields
        fields:
          alt:
            label: Alternative Image Text
            type: text
          artist:
            label: Artist
            type: text
            width: 2/3
          galleryType:
            label: Gallery
            type: select
            width: 1/3
            options:
              - Gallery 1
              - Gallery 2
          link:
            label: Link
            type: url